//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForBelfort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string Description { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Statuses Statuses1 { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
